### ISSUE TITLE
利用規約ページのwidthとheightがおかしい

### ISSUE THREAD

**Issue by ACF37** [nishi-developers/TowerAttackGame#47]
利用規約([https://tower-attack-game.vercel.app/terms](https://tower-attack-game.vercel.app/terms))閲覧時、URLが改行されないためか、スクロールすると白い部分が見える。
AndroidのChrome, Edgeなどで確認。Firefoxでは正常だったのでChromium系の仕様が関連してるかもしれない。

**Comment by M-Haruki** [comment]
word-wrap: break-word;
としてURLを改行させることで治ったはずです
